export enum MAIN_CONTENT {
  FEATURE = 'feature',
  VALUE = 'value',
}

export enum ERROR_TYPE {
  PAGE = 'PAGE',
  PRODUCT = 'PRODUCT',
}

export enum BUTTON_THEME {
  ROUNDED_BUTTON = 'ROUNDED_BUTTON',
  ROUNDED_OUTLINE_BUTTON = 'ROUNDED_OUTLINE_BUTTON',
  FULL_ROUNDED = 'FULL_ROUNDED',
  NAVIGATION = 'NAVIGATION',
}

export enum COLOR_THEME {
  DANGER = 'DANGER',
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  DEFAULT = 'DEFAULT',
  TRANSPARENT = 'TRANSPARENT',
}

export type BUTTON_COLOR_THEME = COLOR_THEME.PRIMARY | COLOR_THEME.DEFAULT | COLOR_THEME.SECONDARY;

export type BADGE_COLOR_THEME = COLOR_THEME.DANGER;

export enum BADGE_THEME {
  DEFAULT = 'DEFAULT',
}
